spring.application.name=pos
# ==========================
# DATASOURCE (H2)
# ==========================
#spring.datasource.url=jdbc:h2:mem:superdb;MODE=MySQL;DB_CLOSE_DELAY=-1
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=root
#spring.datasource.password=
# ==========================
# JPA / HIBERNATE
# ==========================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Para que H2 se porte como MySQL (importante para tests)
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ==========================
# H2 CONSOLE
# ==========================
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Base de datos
spring.datasource.url=jdbc:mariadb://localhost:3306/posref
spring.datasource.username=root
spring.datasource.password=1234qwer
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true